/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PageNameImport } from './routes/$pageName'
import { Route as IndexImport } from './routes/index'
import { Route as EditPageNameImport } from './routes/edit.$pageName'

// Create/Update Routes

const PageNameRoute = PageNameImport.update({
  path: '/$pageName',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EditPageNameRoute = EditPageNameImport.update({
  path: '/edit/$pageName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$pageName': {
      id: '/$pageName'
      path: '/$pageName'
      fullPath: '/$pageName'
      preLoaderRoute: typeof PageNameImport
      parentRoute: typeof rootRoute
    }
    '/edit/$pageName': {
      id: '/edit/$pageName'
      path: '/edit/$pageName'
      fullPath: '/edit/$pageName'
      preLoaderRoute: typeof EditPageNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/edit/$pageName': typeof EditPageNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/edit/$pageName': typeof EditPageNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$pageName': typeof PageNameRoute
  '/edit/$pageName': typeof EditPageNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$pageName' | '/edit/$pageName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$pageName' | '/edit/$pageName'
  id: '__root__' | '/' | '/$pageName' | '/edit/$pageName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageNameRoute: typeof PageNameRoute
  EditPageNameRoute: typeof EditPageNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageNameRoute: PageNameRoute,
  EditPageNameRoute: EditPageNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$pageName",
        "/edit/$pageName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$pageName": {
      "filePath": "$pageName.tsx"
    },
    "/edit/$pageName": {
      "filePath": "edit.$pageName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
